# Generated by Django 6.0 on 2026-01-18 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DarkApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_scroll', models.TextField(help_text='Why should we summon you?', verbose_name='Incantation (Cover Letter)')),
                ('doom_status', models.CharField(choices=[('purgatory', 'In Purgatory (Pending)'), ('ascended', 'Ascended (Accepted)'), ('banished', 'Banished (Rejected)')], default='purgatory', max_length=20, verbose_name='Fate (Status)')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobpost')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('job', 'seeker')},
            },
        ),
    ]
