# Generated by Django 6.0 on 2026-02-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_darkapplication_resume_alter_darkapplication_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darkapplication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
