# Generated by Django 6.0 on 2026-01-18 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Role Title (e.g., Head Witch)', max_length=200)),
                ('description', models.TextField(verbose_name='Grim Details (Description)')),
                ('haunted_ground', models.CharField(max_length=100, verbose_name='Haunted Ground (Location)')),
                ('bounty_gold', models.CharField(help_text='e.g. 500 Gold Coins / Month', max_length=100, verbose_name='Bounty (Salary)')),
                ('contract_type', models.CharField(choices=[('full_moon', 'Full Moon (Full Time)'), ('half_moon', 'Half Moon (Part Time)'), ('eclipse', 'Eclipse (Contract)')], default='full_moon', max_length=20, verbose_name='Moon Phase (Job Type)')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='Summoned Date')),
                ('summoner', models.ForeignKey(limit_choices_to={'reincarnation_type': 'dungeon_master'}, on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Summoner (Employer)')),
            ],
        ),
    ]
