# Generated by Django 6.0 on 2026-01-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curseduser',
            name='reincarnation_type',
            field=models.CharField(choices=[('specter', 'Wandering Specter (Job Seeker)'), ('dungeon_master', 'Dungeon Master (Employer)')], default='specter', help_text='Are you seeking a haunt or do you own the dungeon?', max_length=20, verbose_name='Reincarnation Type (Role)'),
        ),
        migrations.AlterField(
            model_name='soulprofile',
            name='coven_description',
            field=models.TextField(blank=True, verbose_name='Coven Description (Company Description)'),
        ),
        migrations.AlterField(
            model_name='soulprofile',
            name='coven_name',
            field=models.CharField(blank=True, help_text='Company Name', max_length=100, verbose_name='Coven Name (Company Name)'),
        ),
        migrations.AlterField(
            model_name='soulprofile',
            name='coven_website',
            field=models.URLField(blank=True, verbose_name='Coven Website (Company Site)'),
        ),
        migrations.AlterField(
            model_name='soulprofile',
            name='crypt_location',
            field=models.CharField(blank=True, help_text='Where do you haunt?', max_length=255, verbose_name='Crypt Location (Address)'),
        ),
        migrations.AlterField(
            model_name='soulprofile',
            name='dark_arts',
            field=models.TextField(blank=True, help_text='Skills possessed', verbose_name='Dark Arts (Skills)'),
        ),
        migrations.AlterField(
            model_name='soulprofile',
            name='portal_url',
            field=models.URLField(blank=True, help_text='Portfolio URL', verbose_name='Portal URL (Portfolio)'),
        ),
        migrations.AlterField(
            model_name='soulprofile',
            name='resurrection_scroll',
            field=models.FileField(blank=True, help_text='Resume (PDF)', null=True, upload_to='scrolls/', verbose_name='Resurrection Scroll (Resume)'),
        ),
        migrations.AlterField(
            model_name='soulprofile',
            name='telepathy_frequency',
            field=models.CharField(blank=True, help_text='Phone Number', max_length=15, verbose_name='Telepathy Frequency (Phone Number)'),
        ),
    ]
