# Generated by Django 6.0 on 2026-01-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souls', '0002_alter_curseduser_reincarnation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soulprofile',
            name='mortal_name',
            field=models.CharField(blank=True, help_text='The name you use in the living world.', max_length=100, verbose_name='Mortal Name (Full Name)'),
        ),
        migrations.AddField(
            model_name='soulprofile',
            name='years_of_decay',
            field=models.PositiveIntegerField(default=0, help_text='Years of professional experience', verbose_name='Years of Decay (Experience)'),
        ),
        migrations.AlterField(
            model_name='curseduser',
            name='reincarnation_type',
            field=models.CharField(choices=[('specter', 'Wandering Specter (Job Seeker)'), ('dungeon_master', 'Dungeon Master (Employer)')], default='specter', help_text='Are you seeking a haunt (Job Seeker) or do you own the dungeon (Employer)?', max_length=20, verbose_name='Reincarnation Type (Role)'),
        ),
        migrations.AlterField(
            model_name='soulprofile',
            name='coven_description',
            field=models.TextField(blank=True, help_text='Describe your company culture and mission.', verbose_name='Coven Description (Company Description)'),
        ),
        migrations.AlterField(
            model_name='soulprofile',
            name='coven_name',
            field=models.CharField(blank=True, help_text='Name of your organization', max_length=100, verbose_name='Coven Name (Company Name)'),
        ),
        migrations.AlterField(
            model_name='soulprofile',
            name='crypt_location',
            field=models.CharField(blank=True, help_text='Where are you currently based?', max_length=255, verbose_name='Crypt Location (Address/City)'),
        ),
        migrations.AlterField(
            model_name='soulprofile',
            name='dark_arts',
            field=models.TextField(blank=True, help_text='List your skills (e.g., Python, Django, Spellcasting)', verbose_name='Dark Arts (Skills)'),
        ),
        migrations.AlterField(
            model_name='soulprofile',
            name='portal_url',
            field=models.URLField(blank=True, help_text='Link to your portfolio or LinkedIn', verbose_name='Portal URL (Portfolio)'),
        ),
        migrations.AlterField(
            model_name='soulprofile',
            name='resurrection_scroll',
            field=models.FileField(blank=True, help_text='Upload your CV (PDF only)', null=True, upload_to='scrolls/', verbose_name='Resurrection Scroll (Resume)'),
        ),
        migrations.AlterField(
            model_name='soulprofile',
            name='telepathy_frequency',
            field=models.CharField(blank=True, help_text='Contact number', max_length=15, verbose_name='Telepathy Frequency (Phone Number)'),
        ),
    ]
