# Generated by Django 6.0 on 2026-01-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souls', '0003_soulprofile_mortal_name_soulprofile_years_of_decay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soulprofile',
            name='coven_name',
        ),
        migrations.RemoveField(
            model_name='soulprofile',
            name='crypt_location',
        ),
        migrations.RemoveField(
            model_name='soulprofile',
            name='mortal_name',
        ),
        migrations.RemoveField(
            model_name='soulprofile',
            name='telepathy_frequency',
        ),
        migrations.RemoveField(
            model_name='soulprofile',
            name='years_of_decay',
        ),
        migrations.AddField(
            model_name='curseduser',
            name='employer_role',
            field=models.CharField(blank=True, choices=[('hr', 'HR Necromancer (HR Rep)'), ('company', 'Coven Leader (Direct Company)')], max_length=20, null=True, verbose_name='Master Rank (Employer Type)'),
        ),
        migrations.AddField(
            model_name='curseduser',
            name='location',
            field=models.CharField(default='Null', max_length=100, verbose_name='Haunted Ground (Location)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curseduser',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Coven Name (Organization)'),
        ),
        migrations.AddField(
            model_name='curseduser',
            name='phone',
            field=models.CharField(default='Null', max_length=15, verbose_name='Telepathy Freq (Phone Number)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curseduser',
            name='reincarnation_type',
            field=models.CharField(choices=[('specter', 'Wandering Specter (Job Seeker)'), ('dungeon_master', 'Dungeon Master (Employer)')], default='specter', max_length=20, verbose_name='Reincarnation Form (User Role)'),
        ),
        migrations.AlterField(
            model_name='soulprofile',
            name='coven_description',
            field=models.TextField(blank=True, verbose_name='Coven Tales (Company Description)'),
        ),
        migrations.AlterField(
            model_name='soulprofile',
            name='coven_website',
            field=models.URLField(blank=True, verbose_name='Coven Web (Company Site)'),
        ),
        migrations.AlterField(
            model_name='soulprofile',
            name='dark_arts',
            field=models.TextField(blank=True, verbose_name='Dark Arts (Skills & Experience)'),
        ),
        migrations.AlterField(
            model_name='soulprofile',
            name='portal_url',
            field=models.URLField(blank=True, verbose_name='Summoning Portal (Portfolio Link)'),
        ),
        migrations.AlterField(
            model_name='soulprofile',
            name='resurrection_scroll',
            field=models.FileField(blank=True, null=True, upload_to='scrolls/', verbose_name='Resurrection Scroll (Resume PDF)'),
        ),
    ]
