# Generated by Django 6.0 on 2026-02-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souls', '0005_alter_curseduser_id_alter_soulprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='curseduser',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='curseduser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='soulprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
